org: istio
repo: istio
support_release_branching: true
image: gcr.io/istio-testing/build-tools:master-2020-03-05T18-27-04

jobs:
  - name: unit-tests
    command: [entrypoint, make, -e, "T=-v", build, racetest, binaries-test]

  - name: cache-experiment
    requirements: [cache]
    modifiers: [optional, hidden]
    command: [entrypoint, make, -e, "T=-v", build, racetest, binaries-test]

  - name: release-test
    type: presubmit
    command: [entrypoint, prow/release-test.sh]
    requirements: [gcp]

  - name: release
    type: postsubmit
    command: [entrypoint, prow/release-commit.sh]
    requirements: [gcp]

  - name: integ-galley-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.galley.kube.presubmit]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-mixer-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.mixer.kube.presubmit]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-pilot-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.pilot.kube.presubmit]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-security-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.security.kube.presubmit]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-telemetry-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.telemetry.kube.presubmit]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-pilot-k8s-tests-controller
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.pilot.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_USE_OPERATOR_CONTROLLER
        value: "true"

  - name: integ-security-k8s-tests-controller
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.security.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_USE_OPERATOR_CONTROLLER
        value: "true"

  - name: integ-telemetry-k8s-tests-controller
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.telemetry.kube.presubmit]
    requirements: [kind]
    env:
      - name: TEST_USE_OPERATOR_CONTROLLER
        value: "true"

  - name: integ-distroless-k8s-tests
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.kube.reachability]
    requirements: [kind]
    env:
    - name: VARIANT
      value: "distroless"

  - name: integ-conformance-k8s-tests
    type: presubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.conformance.kube.presubmit]
    requirements: [kind]

  - name: integ-local-tests
    command: [entrypoint, prow/integ-suite-local.sh, test.integration...local]
    requirements: [docker]

  - name: integ-galley-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.galley.kube]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-mixer-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.mixer.kube]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-pilot-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.pilot.kube]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-security-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.security.kube]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-telemetry-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.telemetry.kube]
    requirements: [kind]
    env:
    - name: TEST_USE_OPERATOR
      value: "true"

  - name: integ-conformance-k8s-tests
    type: postsubmit
    command: [entrypoint, prow/integ-suite-kind.sh, test.integration.conformance.kube]
    requirements: [kind]

    # The node image must be kept in sync with the kind version we use.
    # See docker/istio/shared/tools/install-golang.sh for the kind image
    # https://github.com/kubernetes-sigs/kind/releases for node corresponding node image
  - name: integ-k8s-114
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.14.10
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "

  - name: integ-k8s-115
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.15.7
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "

  - name: integ-k8s-116
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - kindest/node:v1.16.4
      - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "

  - name: integ-k8s-118
    type: postsubmit
    command:
      - entrypoint
      - prow/integ-suite-kind.sh
      - --node-image
      - gcr.io/istio-testing/kind-node:v1.18.0-beta.1
      - test.integration.kube.presubmit
    requirements: [kind]
    modifiers: [hidden]
    timeout: 4h
    env:
      - name: INTEGRATION_TEST_FLAGS
        value: " --istio.test.retries=1 "

  - name: lint
    type: presubmit
    command: [make, lint]
    resources: lint

  - name: gencheck
    type: presubmit
    command: [make, gen-check]

resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
  lint:
    requests:
      memory: "16Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
